const CATALOG = [
  {
    id: 'el01',
    name: 'Юваль Харари. Sapiens. Краткая история человечества',
    img: '../assets/books/sapiens.png',
    quantity: '15',
    year: '2020',
    cover: 'твердый',
    genre: 'nonfiction',
    publishingHouse: 'Синдбад',
    favorite: true,
  },

  {
    id: 'el02',
    name: 'Эрих Фромм. Искусство любить',
    img: '../assets/books/theArtOfLove.png',
    quantity: '4',
    year: '2022',
    cover: 'мягкий',
    genre: 'nonfiction',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el03',
    name: 'Стивен Хокинг. Теория Всего',
    img: '../assets/books/theTheoryOfEverything.png',
    quantity: '8',
    year: '2022',
    cover: 'твердый',
    genre: 'nonfiction',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el04',
    name: 'Бессел ван дер Колк. Тело помнит все',
    img: '../assets/books/theBodyRemembersEverything.png',
    quantity: '5',
    year: '2020',
    cover: 'мягкий',
    genre: 'nonfiction',
    publishingHouse: 'Эксмо',
    favorite: false,
  },

  {
    id: 'el05',
    name: 'Грег Мортенсон. Три чашки чая',
    img: '../assets/books/threeCupsOfTea.png',
    quantity: '12',
    year: '2021',
    cover: 'твердый',
    genre: 'nonfiction',
    publishingHouse: 'БОМБОРА',
    favorite: false,
  },

  {
    id: 'el06',
    name: 'Виктор Гюго. Труженики моря',
    img: '../assets/books/seaWorkers.png',
    quantity: '15',
    year: '2018',
    cover: 'твердый',
    genre: 'classic',
    publishingHouse: 'RUGRAM',
    favorite: false,
  },

  {
    id: 'el07',
    name: 'Джейн Остен. Гордость и предубеждение',
    img: '../assets/books/PrideAndPrejudice.png',
    quantity: '10',
    year: '2021',
    cover: 'твердый',
    genre: 'classic',
    publishingHouse: 'АСТ',
    favorite: true,
  },

  {
    id: 'el08',
    name: 'Каттон Элеанор. Светила',
    img: '../assets/books/luminaries.png',
    quantity: '6',
    year: '2020',
    cover: 'твердый',
    genre: 'classic',
    publishingHouse: 'Азбука',
    favorite: false,
  },

  {
    id: 'el09',
    name: 'Федор Достоевский. Преступление и наказание',
    img: '../assets/books/CrimeAndPunishment.png',
    quantity: '4',
    year: '2022',
    cover: 'мягкий',
    genre: 'classic',
    publishingHouse: 'АСТ',
    favorite: true,
  },

  {
    id: 'el10',
    name: 'Михаил Шолохов. Тихий Дон',
    img: '../assets/books/quietDon.png',
    quantity: '8',
    year: '2019',
    cover: 'твердый',
    genre: 'classic',
    publishingHouse: 'Азбука',
    favorite: false,
  },

  {
    id: 'el11',
    name: 'Робин Хобб. Ученик убийцы',
    img: '../assets/books/assassinsApprentice.png',
    quantity: '4',
    year: '2022',
    cover: 'твердый',
    genre: 'fantasy',
    publishingHouse: 'Азбука',
    favorite: true,
  },

  {
    id: 'el12',
    name: 'Анджей Сапковский. Ведьмак',
    img: '../assets/books/witcher.png',
    quantity: '13',
    year: '2019',
    cover: 'твердый',
    genre: 'fantasy',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el13',
    name: 'Нил Гейман. Американские боги',
    img: '../assets/books/americanGods.png',
    quantity: '11',
    year: '2022',
    cover: 'твердый',
    genre: 'fantasy',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el14',
    name: 'Толкин Дж.Р.Р. Властелин колец. Хранители кольца',
    img: '../assets/books/LordOfTheRings.png',
    quantity: '2',
    year: '2020',
    cover: 'мягкий',
    genre: 'fantasy',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el15',
    name: 'Мартин Джордж Р.Р. Игра престолов',
    img: '../assets/books/gameOfThrones.png',
    quantity: '4',
    year: '2021',
    cover: 'твердый',
    genre: 'fantasy',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el16',
    name: 'Кинг Стивен. 11/22/63',
    img: '../assets/books/11-22-63.png',
    quantity: '14',
    year: '2020',
    cover: 'мягкий',
    genre: 'horror',
    publishingHouse: 'АСТ',
    favorite: true,
  },

  {
    id: 'el17',
    name: 'Говард Лавкрафт. Ктулху',
    img: '../assets/books/cthulhu.png',
    quantity: '4',
    year: '2021',
    cover: 'твердый',
    genre: 'horror',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el18',
    name: 'Мария Корелли. Скорбь Сатаны',
    img: '../assets/books/satansSorrow.png',
    quantity: '8',
    year: '2022',
    cover: 'мягкий',
    genre: 'horror',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el19',
    name: 'Джо Хилл. Черный телефон',
    img: '../assets/books/blackPhone.png',
    quantity: '6',
    year: '2022',
    cover: 'твердый',
    genre: 'horror',
    publishingHouse: 'Fanzon',
    favorite: false,
  },

  {
    id: 'el20',
    name: 'Джеральд Бром. Косиног: История о колдовстве',
    img: '../assets/books/cosinogh.png',
    quantity: '6',
    year: '2022',
    cover: 'твердый',
    genre: 'horror',
    publishingHouse: 'АСТ',
    favorite: false,
  },

  {
    id: 'el21',
    name: 'Донато Карризи. Девушка в тумане',
    img: '../assets/books/girlInTheFog.png',
    quantity: '1',
    year: '2018',
    cover: 'твердый',
    genre: 'detective',
    publishingHouse: 'Азбука',
    favorite: false,
  },

  {
    id: 'el22',
    name: 'Ричард Осман. Клуб убийств по четвергам',
    img: '../assets/books/ThursdayMurderClub.png',
    quantity: '12',
    year: '2022',
    cover: 'твердый',
    genre: 'detective',
    publishingHouse: 'МИФ',
    favorite: true,
  },

  {
    id: 'el23',
    name: 'Тертон С. Семь смертей Эвелины Хардкасл',
    img: '../assets/books/TheSevenDeathsofEvelynHardcastle.png',
    quantity: '3',
    year: '2020',
    cover: 'мягкий',
    genre: 'detective',
    publishingHouse: 'Азбука',
    favorite: false,
  },

  {
    id: 'el24',
    name: 'Агата Кристи. Смерть на Ниле',
    img: '../assets/books/DeathontheNile.png',
    quantity: '6',
    year: '2022',
    cover: 'Мягкий',
    genre: 'detective',
    publishingHouse: 'Эксмо',
    favorite: true,
  },

  {
    id: 'el25',
    name: 'Гэлбрейт Роберт. Смертельная белизна',
    img: '../assets/books/deadlyWhite.png',
    quantity: '9',
    year: '2020',
    cover: 'Мягкий',
    genre: 'detective',
    publishingHouse: 'Азбука',
    favorite: false,
  }
]
